name: Lint

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pep8-naming
      - name: Lint with flake8
        run: |
          results=$(flake8 . --exit-zero --config=.flake8)
          results="${results//'%'/'%25'}"
          results="${results//$'\n'/'%0A'}"
          results="${results//$'\r'/'%0D'}"
          results_length=${#results}
          echo "::set-output name=flake8_results::$results"
          echo "::set-output name=results_length::$results_length"
        id: lint_run

      - name: Display Results if length > 0
        if: steps.lint_run.outputs.results_length > 0
        run: |
          echo "${{ steps.lint_run.outputs.flake8_results }}"
          exit 1
